a="j'ai une classe de ".upper()+str(30)+"ELEVES".lower()
print(a)
b="hello world".capitalize()
print(b)
c="le monde est méchant".title()
print(c)
d="bonjour bonjour, l'après midi a été long comme le jour d'avant".replace("jour","soir").replace("midi","matinée").replace(" "," ")
print(d)
e="  bonjour  ".strip(" ujor")
print(e)
f="  bonjour  ".rstrip(" ujor")
print(f)
g="  bonjour  ".lstrip(" ujor")
print(g)
h="1, 2, 3, 4, 5".strip(", ")
print(h)
i=(".").join("1, 2, 3, 4, 5".strip(","))
print(i)
j=("2").join(["1,2,3"])
print(j)
for i in range(5):
    print(str(i).zfill(2) )
k="bonjour".islower() 
print(k)
l="Bonjour tout le monde".istitle()
print(l)
m="50".isdigit( )
print(m)
n="Bonjour le jour".count(" jour")
print(n)
o="bonjour le jour".find("jour")
print(o)
p="bonjour le jour".rfind("jour")
print(p)
q  ="bonjour le jour".index("jour")
print(q)
r="bonjour le jour".endswith("jour")
print(r)
s ="bonjour le jour".startswith("jour")
print(s)
